# Generated by Django 3.2.9 on 2022-06-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='video_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='video_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='iframe_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='top_text',
            field=models.TextField(null=True),
        ),
    ]
