# Generated by Django 3.2.9 on 2022-06-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20220624_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='video_text',
        ),
        migrations.RemoveField(
            model_name='home',
            name='video_title',
        ),
    ]
