# Generated by Django 3.2.9 on 2022-06-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20220624_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnAir',
            new_name='PodcastEpisode',
        ),
        migrations.RemoveField(
            model_name='meetteam',
            name='photo_link',
        ),
        migrations.AddField(
            model_name='meetteam',
            name='member_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meetteam',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='meetteam',
            name='writeup',
            field=models.TextField(null=True),
        ),
    ]
