# Generated by Django 3.2.9 on 2022-06-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20220626_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetteam',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
