# Generated by Django 3.2.9 on 2022-06-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_home_iframe_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='iframe_link',
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='video_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='video_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='video_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
