# Generated by Django 3.2.9 on 2022-06-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20220626_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='video_link',
            field=models.TextField(null=True),
        ),
    ]
