# Generated by Django 3.2.9 on 2022-06-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_podcastepisode_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='upload_date',
            field=models.DateTimeField(null=True),
        ),
    ]
